model_parameters:
  model_name: "HuggingFaceTB/SmolLM2-1.7B-Instruct"
  revision: "57aa3c6599c53705406c648e7acca7e11dc45ea3"
  dtype: "float16"
  compile: false
  model_parallel: false
  batch_size: 1
  continuous_batching: false
  model_loading_kwargs:
    attn_implementation: "eager"
    #tp_plan: "auto"
  generation_parameters:
    #num_blocks: 4096
    #block_size: 64
    #max_new_tokens: 256
    temperature: 0.0
    top_p: 0.9
