# Copyright 2024 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from enum import Enum


class Language(Enum):
    english = "en"
    spanish = "es"
    portuguese = "pt"
    italian = "it"
    french = "fr"
    romanian = "ro"
    german = "de"
    latin = "la"
    czech = "cs"
    danish = "da"
    finnish = "fi"
    greek = "el"
    norwegian = "no"
    polish = "pl"
    russian = "ru"
    slovenian = "sl"
    swedish = "sv"
    turkish = "tr"
    dutch = "nl"
    chinese = "zh"
    japanese = "ja"
    vietnamese = "vi"
    indonesian = "id"
    persian = "fa"
    korean = "ko"
    arabic = "ar"
    thai = "th"
    hindi = "hi"
    bengali = "bn"
    tamil = "ta"
    hungarian = "hu"
    ukrainian = "uk"
    slovak = "sk"
    bulgarian = "bg"
    catalan = "ca"
    croatian = "hr"
    serbian = "sr"
    lithuanian = "lt"
    estonian = "et"
    hebrew = "he"
    latvian = "lv"
    serbocroatian = "sh"  # Deprecated
    albanian = "sq"
    azerbaijani = "az"
    icelandic = "is"
    macedonian = "mk"
    georgian = "ka"
    galician = "gl"
    armenian = "hy"
    basque = "eu"
    swahili = "sw"
    malay = "ms"
    tagalog = "tl"
    javanese = "jv"
    punjabi = "pa"
    bihari = "bh"  # Deprecated
    gujarati = "gu"
    yoruba = "yo"
    marathi = "mr"
    urdu = "ur"
    amharic = "am"
    telugu = "te"
    malayalam = "ml"
    kannada = "kn"
    nepali = "ne"
    kazakh = "kk"
    belarusian = "be"
    burmese = "my"
    esperanto = "eo"
    uzbek = "uz"
    khmer = "km"
    tajik = "tg"
    welsh = "cy"
    norwegian_nynorsk = "nn"
    bosnian = "bs"
    sinhala = "si"
    tatar = "tt"
    afrikaans = "af"
    oriya = "or"
    kirghiz = "ky"
    irish = "ga"
    occitan = "oc"
    kurdish = "ku"
    lao = "lo"
    luxembourgish = "lb"
    bashkir = "ba"
    western_frisian = "fy"
    pashto = "ps"
    maltese = "mt"
    breton = "bt"
    assamese = "as"
    malagasy = "mg"
    divehi = "dv"
    yiddish = "yi"
    somali = "so"
    sanskrit = "sa"
    sindhi = "sd"
    turkmen = "tk"
    south_azerbaijani = "azb"
    sorani = "ckb"
    cebuano = "ceb"
    war = "war"
