name: PR Style Bot

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

jobs:
  style:
    uses: huggingface/huggingface_hub/.github/workflows/style-bot-action.yml@ed9b560885ce974da9c0742a29ce1484b263e184
    with:
      python_quality_dependencies: "[quality]"
    secrets:
      bot_token: ${{ secrets.HF_STYLE_BOT_ACTION }}
