name: PR Style Bot

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  style:
    uses: huggingface/huggingface_hub/.github/workflows/style-bot-action.yml@d85775c1a16f9cec2df3af89bebcb30976fdab79
    with:
      python_quality_dependencies: "[quality]"
    secrets:
      bot_token: ${{ secrets.HF_STYLE_BOT_ACTION }}
