name: PR Style Bot

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  style:
    uses: huggingface/huggingface_hub/.github/workflows/style-bot-action.yml@d87e6e68f8edeab7aa706e88c47f4039744707e9
    with:
      python_quality_dependencies: "[quality]"
    secrets:
      bot_token: ${{ secrets.HF_STYLE_BOT_ACTION }}
