name: Tests

on:
  push:
    branches:
      - main
      - v*-release
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          lfs: true

      - name: Cache Hugging Face models
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: cache/models
          key: hf-models-${{ runner.os }}-${{ github.ref }}
          restore-keys: hf-models-${{ runner.os }}-

      - name: Cache Hugging Face datasets
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: cache/datasets
          key: hf-datasets-${{ runner.os }}-${{ github.ref }}
          restore-keys: hf-datasets-${{ runner.os }}-

      - name: Cache uv virtual environment
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .venv
          key: uv-env-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: uv-env-${{ runner.os }}-

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --extra dev-gpu

      - name: Ensure cache directories exist
        run: mkdir -p cache/models cache/datasets

      - name: Run tests
        env:
          HF_TEST_TOKEN: ${{ secrets.HF_TEST_TOKEN }}
          HF_HOME: "cache/models"
          HF_DATASETS_CACHE: "cache/datasets"
        run: uv run pytest -x --disable-pytest-warnings
